/** Full Habibi Restaurant menu from printed menu */

const M = (file) => `/menu/items/${file}`;

export const MENU_IMAGES = {
  catBurgers: '/menu/categories/cat-burgers.png',
  catShawarma: '/menu/categories/cat-shawarma.png',
  catRice: '/menu/categories/cat-rice.png',
  catPlatter: '/menu/categories/cat-platter.png',
  catBbq: '/menu/categories/cat-bbq.png',
  catKarahi: '/menu/categories/cat-karahi.png',
  catSalan: '/menu/categories/cat-salan.png',
  catExtras: '/menu/categories/cat-extras.png',
  chickenBurger: M('chicken-burger.png'),
  zingerBurger: M('zinger-burger.png'),
  andaShami: M('anda-shami-burger.png'),
  chickenSandwich: M('chicken-sandwich.png'),
  shawarmaWrap: M('shawarma-wrap.png'),
  openShawarma: M('open-shawarma.png'),
  platterShawarma: M('platter-shawarma.png'),
  biryani: M('biryani.png'),
  kabuliPulao: M('kabuli-pulao.png'),
  friedRice: M('fried-rice.png'),
  vegFriedRice: M('veg-fried-rice.png'),
  eggFriedRice: M('egg-fried-rice.png'),
  masalaFriedRice: M('masala-fried-rice.png'),
  normalPlatter: M('normal-platter.png'),
  halfPlatter: M('half-platter.png'),
  fullPlatter: M('full-platter.png'),
  chargahPlatter: M('chargah-platter.png'),
  chargahDeal: M('chargah-deal.png'),
  beefTikka: M('beef-tikka.png'),
  beefSeekh: M('beef-seekh.png'),
  chickenSeekh: M('chicken-seekh.png'),
  malaiBoti: M('malai-boti.png'),
  chickenBoti: M('chicken-boti.png'),
  fullChicken: M('full-chicken.png'),
  chickenChest: M('chicken-chest.png'),
  chickenLeg: M('chicken-leg.png'),
  chickenHandi: M('chicken-handi.png'),
  whiteHandi: M('white-handi.png'),
  acharHandi: M('achar-handi.png'),
  chickenKarahi: M('chicken-karahi.png'),
  muttonKarahi: M('mutton-karahi.png'),
  beefKarahi: M('beef-karahi.png'),
  lahoriChargah: M('lahori-chargah.png'),
  chickenKorma: M('chicken-korma.png'),
  chickenAchari: M('chicken-achari.png'),
  kababKarahi: M('kabab-karahi.png'),
  namkeenRosh: M('namkeen-rosh.png'),
  beefKeema: M('beef-keema.png'),
  chana: M('chana.png'),
  lobiya: M('lobiya.png'),
  sabzi: M('sabzi.png'),
  raita: '/menu/categories/cat-extras.png',
  salad: '/menu/categories/cat-extras.png',
  shamiKabab: M('beef-seekh.png'),
  chickenWings: M('malai-boti.png'),
};

const I = MENU_IMAGES;

export const MENU_CATEGORIES = [
  { id: 1, name: 'Burgers', image: I.catBurgers, sort_order: 0 },
  { id: 2, name: 'Chicken Shawarma', image: I.catShawarma, sort_order: 1 },
  { id: 3, name: 'Rice', image: I.catRice, sort_order: 2 },
  { id: 4, name: 'Platter', image: I.catPlatter, sort_order: 3 },
  { id: 5, name: 'BBQ', image: I.catBbq, sort_order: 4 },
  { id: 6, name: 'Karahi & Handi', image: I.catKarahi, sort_order: 5 },
  { id: 7, name: 'Salan Plate', image: I.catSalan, sort_order: 6 },
  { id: 8, name: 'Extras', image: I.catExtras, sort_order: 7 },
];

export const MENU_ITEMS = [
  { id: 1, category_id: 1, name: 'Chicken Burger', description: '', price: 150, image: I.chickenBurger, sort_order: 0 },
  { id: 2, category_id: 1, name: 'Zinger Burger', description: '', price: 300, image: I.zingerBurger, sort_order: 1 },
  { id: 3, category_id: 1, name: 'Anda Shami Burger', description: '', price: 150, image: I.andaShami, sort_order: 2 },
  { id: 4, category_id: 1, name: 'Chicken Sandwich', description: '', price: 80, image: I.chickenSandwich, sort_order: 3 },

  { id: 5, category_id: 2, name: 'Chicken Shawarma', description: '', price: 150, image: I.shawarmaWrap, sort_order: 0 },
  { id: 6, category_id: 2, name: 'Open Plat Shawarma', description: '', price: 250, image: I.openShawarma, sort_order: 1 },
  { id: 7, category_id: 2, name: 'Platter Shawarma', description: '', price: 300, image: I.platterShawarma, sort_order: 2 },

  { id: 8, category_id: 3, name: 'Baryani Full', description: '', price: 400, image: I.biryani, sort_order: 0 },
  { id: 9, category_id: 3, name: 'Baryani Half', description: '', price: 200, image: I.biryani, sort_order: 1 },
  { id: 10, category_id: 3, name: 'Kabuli Pulao Full', description: '', price: 400, image: I.kabuliPulao, sort_order: 2 },
  { id: 11, category_id: 3, name: 'Kabuli Pulao Half', description: '', price: 200, image: I.kabuliPulao, sort_order: 3 },
  { id: 12, category_id: 3, name: 'Fried Rice', description: '', price: 450, image: I.friedRice, sort_order: 4 },
  { id: 13, category_id: 3, name: 'Vegetable Fried Rice', description: '', price: 430, image: I.vegFriedRice, sort_order: 5 },
  { id: 14, category_id: 3, name: 'Egg Fried Rice', description: '', price: 480, image: I.eggFriedRice, sort_order: 6 },
  { id: 15, category_id: 3, name: 'Special Masala Fried Rice', description: '', price: 500, image: I.masalaFriedRice, sort_order: 7 },

  { id: 16, category_id: 4, name: 'Normal Platter', description: '+ Rs. 500', price: 2500, image: I.normalPlatter, sort_order: 0 },
  { id: 17, category_id: 4, name: 'Half Platter', description: '+ Rs. 500', price: 3800, image: I.halfPlatter, sort_order: 1 },
  { id: 18, category_id: 4, name: 'Full Platter', description: '+ Rs. 500', price: 7000, image: I.fullPlatter, sort_order: 2 },
  { id: 19, category_id: 4, name: 'Dagi Chargaa Normal Platter', description: '+ Rs. 500', price: 3000, image: I.chargahPlatter, sort_order: 3 },
  { id: 20, category_id: 4, name: 'Dagi Chargaa Half Platter', description: '+ Rs. 500', price: 5000, image: I.chargahPlatter, sort_order: 4 },
  { id: 21, category_id: 4, name: 'Dagi Chargaa Deal', description: '+ Rs. 250', price: 2000, image: I.chargahDeal, sort_order: 5 },

  { id: 22, category_id: 5, name: 'Beef Tikka', description: '', price: 150, image: I.beefTikka, sort_order: 0 },
  { id: 23, category_id: 5, name: 'Beef Seekh Kabab', description: '', price: 180, image: I.beefSeekh, sort_order: 1 },
  { id: 24, category_id: 5, name: 'Chicken Seekh Rashme Kabab', description: '', price: 180, image: I.chickenSeekh, sort_order: 2 },
  { id: 25, category_id: 5, name: 'Chicken Malai Boti', description: '', price: 800, image: I.malaiBoti, sort_order: 3 },
  { id: 26, category_id: 5, name: 'Chicken Boti', description: '', price: 700, image: I.chickenBoti, sort_order: 4 },
  { id: 27, category_id: 5, name: 'Full Chicken', description: '', price: 1450, image: I.fullChicken, sort_order: 5 },
  { id: 28, category_id: 5, name: 'Chicken Chest Piece', description: '', price: 380, image: I.chickenChest, sort_order: 6 },
  { id: 29, category_id: 5, name: 'Chicken Leg Piece', description: '', price: 360, image: I.chickenLeg, sort_order: 7 },

  { id: 30, category_id: 6, name: 'Chicken Handi Full', description: '', price: 1600, image: I.chickenHandi, sort_order: 0 },
  { id: 31, category_id: 6, name: 'Chicken Handi Half', description: '', price: 800, image: I.chickenHandi, sort_order: 1 },
  { id: 32, category_id: 6, name: 'Chicken White Handi Full', description: '', price: 1700, image: I.whiteHandi, sort_order: 2 },
  { id: 33, category_id: 6, name: 'Chicken White Handi Half', description: '', price: 850, image: I.whiteHandi, sort_order: 3 },
  { id: 34, category_id: 6, name: 'Chicken Achar Handi Full', description: '', price: 1700, image: I.acharHandi, sort_order: 4 },
  { id: 35, category_id: 6, name: 'Chicken Achar Handi Half', description: '', price: 850, image: I.acharHandi, sort_order: 5 },
  { id: 36, category_id: 6, name: 'Chicken Karahi Full', description: '', price: 1500, image: I.chickenKarahi, sort_order: 6 },
  { id: 37, category_id: 6, name: 'Chicken Karahi Half', description: '', price: 750, image: I.chickenKarahi, sort_order: 7 },
  { id: 38, category_id: 6, name: 'Mutton Karahi Full', description: '', price: 2800, image: I.muttonKarahi, sort_order: 8 },
  { id: 39, category_id: 6, name: 'Beef Tikka Karahi Full', description: '', price: 2000, image: I.beefKarahi, sort_order: 9 },
  { id: 40, category_id: 6, name: 'Beef Tikka Karahi Half', description: '', price: 1000, image: I.beefKarahi, sort_order: 10 },
  { id: 41, category_id: 6, name: 'Dagi Chargaa', description: '', price: 1350, image: I.lahoriChargah, sort_order: 11 },

  { id: 42, category_id: 7, name: 'Chicken Korma', description: '', price: 200, image: I.chickenKorma, sort_order: 0 },
  { id: 43, category_id: 7, name: 'Chicken Achari', description: '', price: 200, image: I.chickenAchari, sort_order: 1 },
  { id: 44, category_id: 7, name: 'Kabab Karahi', description: '', price: 200, image: I.kababKarahi, sort_order: 2 },
  { id: 45, category_id: 7, name: 'Beef Namkeen Rosh', description: '', price: 250, image: I.namkeenRosh, sort_order: 3 },
  { id: 46, category_id: 7, name: 'Chicken Namkeen Rosh', description: '', price: 250, image: I.namkeenRosh, sort_order: 4 },
  { id: 47, category_id: 7, name: 'Beef Keema', description: '', price: 250, image: I.beefKeema, sort_order: 5 },
  { id: 48, category_id: 7, name: 'Chana', description: '', price: 150, image: I.chana, sort_order: 6 },
  { id: 49, category_id: 7, name: 'Lobiya', description: '', price: 150, image: I.lobiya, sort_order: 7 },
  { id: 50, category_id: 7, name: 'Sabzi', description: '', price: 150, image: I.sabzi, sort_order: 8 },

  { id: 51, category_id: 8, name: 'Raita', description: '', price: 30, image: I.raita, sort_order: 0 },
  { id: 52, category_id: 8, name: 'Salad', description: '', price: 30, image: I.salad, sort_order: 1 },
  { id: 53, category_id: 8, name: 'Shami Kabab', description: '', price: 50, image: I.shamiKabab, sort_order: 2 },
  { id: 54, category_id: 8, name: 'Chicken Wings', description: '', price: 60, image: I.chickenWings, sort_order: 3 },
];

export const MENU_OFFERS = [
  {
    id: 1,
    title: 'Dagi Chargaa Deal',
    description: 'Crispy Lahori chargah special deal — order now on WhatsApp! (+ Rs. 250)',
    price: 2000,
    image: I.chargahDeal,
    sort_order: 0,
  },
  {
    id: 2,
    title: 'Normal BBQ Platter',
    description: 'Mixed grill platter for family — chicken tikka, seekh kabab & more (+ Rs. 500)',
    price: 2500,
    image: I.normalPlatter,
    sort_order: 1,
  },
  {
    id: 3,
    title: 'Full Family Platter',
    description: 'Our biggest platter — perfect for gatherings (+ Rs. 500)',
    price: 7000,
    image: I.fullPlatter,
    sort_order: 2,
  },
];

export const MENU_SPECIAL_DISHES = [
  {
    id: 1,
    name: 'Dagi Chargaa',
    description: 'Crispy whole Lahori chargah — Habibi\'s signature specialty.',
    price: 1350,
    image: I.lahoriChargah,
    sort_order: 0,
  },
  {
    id: 2,
    name: 'Chicken Karahi Full',
    description: 'Sizzling chicken karahi with tomatoes, ginger and green chilies.',
    price: 1500,
    image: I.chickenKarahi,
    sort_order: 1,
  },
  {
    id: 3,
    name: 'Baryani Full',
    description: 'Aromatic basmati rice with spiced chicken — full portion.',
    price: 400,
    image: I.biryani,
    sort_order: 2,
  },
  {
    id: 4,
    name: 'Zinger Burger',
    description: 'Crispy spicy chicken burger — customer favourite.',
    price: 300,
    image: I.zingerBurger,
    sort_order: 3,
  },
];
